name: video_editor_example
description: The example project for the video_editor package.

publish_to: "none" 
version: 3.0.0+1

environment:
  flutter: ">=3.0.0"
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  video_editor:
    path: ../

  fraction: ^5.0.4
  image_picker: ^1.1.2
  path: ^1.8.2
  video_player: ^2.6.1
  ffmpeg_kit_flutter_min: any
  

flutter:
  uses-material-design: true

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1